### PR TITLE
emit event as const by default, add `_mut` variants.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This doesn't change the observe-side.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
It seems better to default to non-`mut` by default and things that require `mut` have a `_mut` suffix.

**Comment by Indra-db** [comment]
seems like a good change to me & the rust way (using _mut)

**Comment by waywardmonkeys** [comment]
Not sure which things to do further ... the observe side needs a lot of work, but this part here works as it is.

**Comment by Indra-db** [comment]
Did some of the changes you proposed. If there's anything else, do let me know :D

**Pull request closed without merging**
